// ---------------  All The NAME   Constant   String -----------

enum EnumLocale {
  appName,
  signupText,
  loginText,
  emailHint,
  passwordHint,
  weakPassword,
  emailAlreadyExists,
  emailRequiredText,
  invalidEmailText,
  passwordRequiredText,
  passwordLengthText,
  passwordUppercaseRequiredText,
  passwordLowercaseRequiredText,
  passwordDigitRequiredText,
  passwordSpecialCharacterRequiredText,
  registeringDescriptionText1,
  registeringDescriptionText2,
  registeringDescriptionText3,
  registeringDescriptionText4,

  acceptPolicyAndCondition,
  doNotHaveAccount,
  alreadyHaveAccount,
  privacyTitle,
  privacyBody,
  conditionOfUseTitle,
  conditionOfUseBody,
  userNotFoundError,
  wrongPasswordError,
  defaultError,
  loginWithGoogle,
  forgotPassword,
  passwordResetInstruction,
  rememberPassword,
  sendButtonText,
  emailSent,
  checkEmail,
  didNotReceiveTheLink,
  resend,
  verifyEmailTitle,
  verifyEmailBody,
  verifyYourEmailText,
  deleteAccountText,
  delete,
  deleteSuccessful,
  loginSuccessful,
  signupSuccessful,
  emailVerifyRequired,
  welcome,
  welcomeDescriptionText,
  next,
  locationPermissionRequired,
  nameHintText,
  nameTitle,
  nameDescription,
  pseudoRequired,
  pseudoLengthError,
  pseudoOnlyContains,
  genderTitle,
  genderDescription,
  genderMale,
  genderFemale,
  dobTitle,
  dobDescription,
  setYourDob,
  ageErrorText,
  addressTitle,
  addressDescription,
  countryName,
  cityName,

  // Interests
  friendshipInterests,
  loveAndRomanceInterests,
  passionAndPersonalityInterests,
  sportsAndOutdoorsInterests,
  foodAndRestaurantsInterests,
  adventureAndTravelInterests,
  interestTitle,
  interestsRequired,
  chooseOption,
  passion,

  // Tags or interest types
  music,
  creativity,
  fitness,
  travel,
  fashion,
  chatting,
  makingNewFriends,
  studyBuddy,
  movieNights,
  coffeeHangouts,
  romanticDates,
  candlelight,
  sweet,
  slowDancing,
  loveLetters,
  football,
  yoga,
  hiking,
  running,
  cycling,
  foodie,
  streetFood,
  fineDining,
  coffeeLover,
  baking,
  backpacking,
  roadTrips,
  soloTravel,
  camping,
  cityBreaks,

  // Image and description
  selectLimit,
  uploadImageTitle,
  uploadImageDescription,
  submit,
  storagePermissionRequired,
  photosPermissionDeniedText,
  descriptionTitle,
  descriptionBody,
  descriptionLabelText,

  // Time-related
  joinedJustNow,
  joined,
  minutesAgo,
  hoursAgo,
  daysAgo,
  ago,
  joinedOn,

  // Settings
  settings,
  logout,
  notifications,
  privacySettings,
  helpCenter,
  changeLanguage,
  favorites,
  archive,
  block,
  report,
  more,
  blocked,
  addStory,
  like,
  message,
  Favorite,
  blockTitle,

  yesBlock,
  cancel,
  yourStory,
  addPhoto,
  savedToFavorites,
  removedFromFavorites,
  removed,
  storyAdded,
  noDataFound,
  follow,
  following,
  noDataAvailable,
  addedToBlock,
  removedFromBlock,
  unblock,
  addedToArchive,
  removedFromArchive,
  unArchive,
  chats,
  online,
  messagesHint,
  lastSeen,
  typing,
  offline,
  noRecentChats,
  atLeastTwoUsers,
  wrongCredential,

  // reporting
  whyAreYouReporting,
  notRevealIdentity,
  reportDescription1,
  reportDescription2,

  violationOfGuidenlines,
  unLawfulContent,

  //---guideline violation------------
  violationOfGuidenlinesTitle,
  underAge,
  depictionOfViolation,
  incorrectProfileDetails,
  abusiveOrIntrusiveBehavior,
  sexualContent,
  spamOrAdvertising,
  dubiousOffers,
  drugs,
  someoneIsInDanger,

  //--------illegel content---------------
  illegalContentTitle,
  invasionOfPrivacy,
  attemptedFraud,
  threadsOrMalliciousStatements,
  sexualHarassment,
  childrenAreAtRisk,
  drugTrafficking,
  racismOrTerrorism,
  blackmail,
  deprivationOfLiberty,
  //------send report ----------
  sendReportTitle,
  emailConfirmation,
  sendReport,
  thankForReport,
  thankForReportDescription,
  done,
  // delete  chatroom
  deleteChatRoom,

  // refresh 
  refreshToUpdatedData ,
  
}

// debug
// keytool -list -v -keystore %USERPROFILE%\.android\debug.keystore -alias androiddebugkey -storepass android -keypass android*/

// release
//keytool -genkey -v -keystore my_release_key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my_key_alias
