name: reels
description: "reels"
version: 0.0.9+4


environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  get: ^4.7.2
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2
  http: ^1.4.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0